version: '3'

services:
  gateway:
    container_name: apigateway
    build: ./apigateway
    image: apigateway
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    ports:
      - '8080:8080'
    depends_on:
      - discovery-server
      - firstservice
      - secondservice
    networks:
      - app_net

  discovery-server:
    container_name: discovery-server
    build: ./eurekaserver
    image: discovery-server
    ports:
      - '8761:8761'
    networks:
      - app_net

  firstservice:
    container_name: firstservice
    build: ./firstservice
    image: firstservice
    environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
        - spring.profiles.active=docker
    ports:
      - '10100:10100'
    depends_on:
      - discovery-server
    networks:
      - app_net

  secondservice:
    container_name: secondservice
    build: ./secondservice
    image: secondservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - spring.profiles.active=docker
    ports:
      - '10101:10101'
    depends_on:
      - discovery-server
    networks:
      - app_net

networks:
    app_net:
        driver: bridge