server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://discovery_server:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: first-service
          uri: lb://first-service-app
          predicates:
            - Path=/firstservice/**
        - id: second-service
          uri: lb://second-service-app
          predicates:
            - Path=/secondservice/**

