server:
  port: 8080
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://first-service-app
          predicates:
            - Path=/firstservice/**
        - id: second-service
          uri: lb://second-service-app
          predicates:
            - Path=/secondservice/**

