server:
  port: 10101

spring:
  application:
    name: second-service-app

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery_server:8761/eureka}