server:
  port: 10101

spring:
  application:
    name: second-service-app

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka